#!/usr/bin/env python3
from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path


CC_THRESHOLD = 8

SKIP_PATH_SEGMENTS = ("migrations", "playground")
SKIP_FILENAME_SUFFIXES = ("_pb2.py", "_pb2_grpc.py")
HEADER_SCAN_LINES = 5
GENERATED_HEADER_PATTERNS = (
    re.compile(r"@generated", re.IGNORECASE),
    re.compile(r"generated by", re.IGNORECASE),
    re.compile(r"do not edit", re.IGNORECASE),
)

DECISION_NODES = (
    ast.If,
    ast.For,
    ast.AsyncFor,
    ast.While,
    ast.ExceptHandler,
    ast.IfExp,
    ast.match_case,
)
SCOPE_NODES = (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda)


def is_skipped_path(path: str) -> bool:
    p = Path(path)
    if p.suffix != ".py":
        return True
    if any(seg in SKIP_PATH_SEGMENTS for seg in p.parts):
        return True
    if any(p.name.endswith(suffix) for suffix in SKIP_FILENAME_SUFFIXES):
        return True
    return False


def is_generated_content(text: str) -> bool:
    header = "\n".join(text.splitlines()[:HEADER_SCAN_LINES])
    return any(pattern.search(header) for pattern in GENERATED_HEADER_PATTERNS)


def existing_file_text(path: str) -> str:
    try:
        return Path(path).read_text()
    except (FileNotFoundError, IsADirectoryError, PermissionError, UnicodeDecodeError):
        return ""


def edit_states(payload: dict) -> tuple[str, str, str]:
    tool = payload.get("tool_name", "")
    inp = payload.get("tool_input", {}) or {}
    path = inp.get("file_path", "")

    if tool == "Write":
        return path, existing_file_text(path), inp.get("content", "")

    if tool == "Edit":
        old_text = existing_file_text(path)
        new_text = old_text.replace(inp.get("old_string", ""), inp.get("new_string", ""), 1)
        return path, old_text, new_text

    if tool == "MultiEdit":
        old_text = existing_file_text(path)
        new_text = old_text
        for edit in inp.get("edits", []) or []:
            new_text = new_text.replace(edit.get("old_string", ""), edit.get("new_string", ""), 1)
        return path, old_text, new_text

    return "", "", ""


def _node_contribution(node: ast.AST) -> int:
    if isinstance(node, DECISION_NODES):
        return 1
    if isinstance(node, ast.BoolOp):
        return len(node.values) - 1
    if isinstance(node, ast.comprehension):
        return len(node.ifs)
    return 0


def cyclomatic_complexity(func_node: ast.AST) -> int:
    cc = 1

    def visit(node: ast.AST) -> None:
        nonlocal cc
        cc += _node_contribution(node)
        for child in ast.iter_child_nodes(node):
            if isinstance(child, SCOPE_NODES):
                continue
            visit(child)

    for child in ast.iter_child_nodes(func_node):
        if isinstance(child, SCOPE_NODES):
            continue
        visit(child)
    return cc


def function_complexities(text: str) -> dict[str, tuple[str, int]]:
    if not text:
        return {}
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return {}
    lines = text.splitlines()
    results: dict[str, tuple[str, int]] = {}
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.body:
            start = node.body[0].lineno
            end = node.end_lineno or start
            body = "\n".join(lines[start - 1:end])
            results[node.name] = (body, cyclomatic_complexity(node))
    return results


def complex_touched_functions(old_text: str, new_text: str) -> list[tuple[str, int]]:
    new_funcs = function_complexities(new_text)
    old_funcs = function_complexities(old_text)
    flagged: list[tuple[str, int]] = []
    for name, (body, cc) in new_funcs.items():
        if cc <= CC_THRESHOLD:
            continue
        previous = old_funcs.get(name)
        if previous is None or previous[0] != body:
            flagged.append((name, cc))
    return flagged


def format_reminder(flagged: list[tuple[str, int]]) -> str:
    listed = ", ".join(f"{name} (CC={cc})" for name, cc in flagged)
    return (
        f"High cyclomatic complexity: {listed}. "
        f"Threshold is {CC_THRESHOLD}. "
        "Extract guard clauses, split branches into named helpers, "
        "or replace if/elif chains with dispatch tables."
    )


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        return 0

    path, old_text, new_text = edit_states(payload)
    if not path or is_skipped_path(path):
        return 0
    if is_generated_content(old_text) or is_generated_content(new_text):
        return 0

    flagged = complex_touched_functions(old_text, new_text)
    if not flagged:
        return 0

    output = {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "allow",
            "additionalContext": format_reminder(flagged),
        }
    }
    print(json.dumps(output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
