#!/usr/bin/env python3
from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path


SKIP_PATH_SEGMENTS = ("migrations", "playground")
SKIP_FILENAME_SUFFIXES = ("_pb2.py", "_pb2_grpc.py")
HEADER_SCAN_LINES = 5
GENERATED_HEADER_PATTERNS = (
    re.compile(r"@generated", re.IGNORECASE),
    re.compile(r"generated by", re.IGNORECASE),
    re.compile(r"do not edit", re.IGNORECASE),
)
SELF_LIKE_NAMES = ("self", "cls")
RETURN_LABEL = "-> return"


def is_skipped_path(path: str) -> bool:
    p = Path(path)
    if p.suffix != ".py":
        return True
    if any(seg in SKIP_PATH_SEGMENTS for seg in p.parts):
        return True
    if any(p.name.endswith(suffix) for suffix in SKIP_FILENAME_SUFFIXES):
        return True
    return False


def is_generated_content(text: str) -> bool:
    header = "\n".join(text.splitlines()[:HEADER_SCAN_LINES])
    return any(pattern.search(header) for pattern in GENERATED_HEADER_PATTERNS)


def existing_file_text(path: str) -> str:
    try:
        return Path(path).read_text()
    except (FileNotFoundError, IsADirectoryError, PermissionError, UnicodeDecodeError):
        return ""


def edit_states(payload: dict) -> tuple[str, str, str]:
    tool = payload.get("tool_name", "")
    inp = payload.get("tool_input", {}) or {}
    path = inp.get("file_path", "")

    if tool == "Write":
        return path, existing_file_text(path), inp.get("content", "")

    if tool == "Edit":
        old_text = existing_file_text(path)
        new_text = old_text.replace(inp.get("old_string", ""), inp.get("new_string", ""), 1)
        return path, old_text, new_text

    if tool == "MultiEdit":
        old_text = existing_file_text(path)
        new_text = old_text
        for edit in inp.get("edits", []) or []:
            new_text = new_text.replace(edit.get("old_string", ""), edit.get("new_string", ""), 1)
        return path, old_text, new_text

    return "", "", ""


def missing_annotations(func: ast.FunctionDef | ast.AsyncFunctionDef) -> list[str]:
    args = func.args
    missing = _missing_positional(args)
    if args.vararg and args.vararg.annotation is None:
        missing.append(f"*{args.vararg.arg}")
    for arg in args.kwonlyargs:
        if arg.annotation is None:
            missing.append(arg.arg)
    if args.kwarg and args.kwarg.annotation is None:
        missing.append(f"**{args.kwarg.arg}")
    if func.returns is None:
        missing.append(RETURN_LABEL)
    return missing


def _missing_positional(args: ast.arguments) -> list[str]:
    positional = list(args.posonlyargs) + list(args.args)
    skip_first = bool(positional) and positional[0].arg in SELF_LIKE_NAMES
    missing: list[str] = []
    for index, arg in enumerate(positional):
        if skip_first and index == 0:
            continue
        if arg.annotation is None:
            missing.append(arg.arg)
    return missing


def function_signatures(text: str) -> dict[str, tuple[str, list[str]]]:
    if not text:
        return {}
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return {}
    lines = text.splitlines()
    results: dict[str, tuple[str, list[str]]] = {}
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            start = node.lineno
            end = node.end_lineno or start
            slice_text = "\n".join(lines[start - 1:end])
            results[node.name] = (slice_text, missing_annotations(node))
    return results


def touched_unannotated(old_text: str, new_text: str) -> list[tuple[str, list[str]]]:
    new_funcs = function_signatures(new_text)
    old_funcs = function_signatures(old_text)
    flagged: list[tuple[str, list[str]]] = []
    for name, (slice_text, missing) in new_funcs.items():
        if not missing:
            continue
        previous = old_funcs.get(name)
        if previous is None or previous[0] != slice_text:
            flagged.append((name, missing))
    return flagged


def format_reminder(flagged: list[tuple[str, list[str]]]) -> str:
    parts = [f"{name} (missing: {', '.join(items)})" for name, items in flagged]
    return (
        f"Missing type annotations: {'; '.join(parts)}. "
        "Add hints for every parameter (except self/cls) and the return type."
    )


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        return 0

    path, old_text, new_text = edit_states(payload)
    if not path or is_skipped_path(path):
        return 0
    if is_generated_content(old_text) or is_generated_content(new_text):
        return 0

    flagged = touched_unannotated(old_text, new_text)
    if not flagged:
        return 0

    output = {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "allow",
            "additionalContext": format_reminder(flagged),
        }
    }
    print(json.dumps(output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
