import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

import { flagCrapViolations } from "./crap.ts";
import type { CrapFunction, CrapViolation } from "./crap.ts";
import type { Snapshot } from "./coverage-v8.ts";
import { detectLang } from "./lang.ts";
import { typescriptExtractor } from "./extract-typescript.ts";

const DEFAULT_THRESHOLD = 10;
const HEADER_SCAN_LINES = 5;
const GENERATED_HEADER_RE = /@generated|generated by|do not edit/i;
const HUNK_HEADER_RE = /^@@ [^@]* \+(\d+)(?:,(\d+))? @@/;

const SKIP_PATH_SEGMENTS = new Set(["node_modules", "playground", "scripts", "bin", "tools"]);
const SKIP_FILE_RE = /\.(test|spec)\.(ts|tsx|mts|cts)$|\.d\.(ts|cts|mts)$/;

const MISSING_SNAPSHOT_MSG = "crap: no coverage snapshot found — run tests with coverage first.";
const STALE_SNAPSHOT_MSG = "crap: coverage data is stale — re-run tests before committing.";

export interface CrapAdapter {
  snapshotExists(): boolean;
  snapshotMtime(): number;
  loadSnapshot(): Snapshot;
  extractFunctions(filePath: string, source: string): CrapFunction[];
}

export interface CrapResult {
  status: number;
  stderr: string;
}

function gitText(cwd: string, args: string[]): string {
  const res = spawnSync("git", args, { cwd, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
  if (res.status !== 0) throw new Error(`git ${args.join(" ")} failed: ${res.stderr}`);
  return res.stdout;
}

function stagedFiles(cwd: string): string[] {
  const out = gitText(cwd, ["diff", "--cached", "--name-only", "--diff-filter=AM", "-z"]);
  return out.split("\0").filter((p) => p.length > 0);
}

function isSkippedPath(rel: string): boolean {
  const norm = rel.replace(/\\/g, "/");
  if (SKIP_FILE_RE.test(norm)) return true;
  for (const seg of norm.split("/")) {
    if (seg.length === 0) continue;
    if (seg.startsWith(".")) return true;
    if (SKIP_PATH_SEGMENTS.has(seg)) return true;
  }
  return false;
}

function isGeneratedContent(text: string): boolean {
  const header = text.split("\n", HEADER_SCAN_LINES).join("\n");
  return GENERATED_HEADER_RE.test(header);
}

function parseHunkRanges(diffText: string): [number, number][] {
  const ranges: [number, number][] = [];
  for (const line of diffText.split("\n")) {
    const m = HUNK_HEADER_RE.exec(line);
    if (m === null || m[1] === undefined) continue;
    const start = Number(m[1]);
    const length = m[2] === undefined ? 1 : Number(m[2]);
    if (length === 0) continue;
    ranges.push([start, start + length - 1]);
  }
  return ranges;
}

function readSource(cwd: string, rel: string): string | null {
  try {
    return fs.readFileSync(path.join(cwd, ...rel.split("/")), "utf8");
  } catch {
    return null;
  }
}

function extractCrapFunctions(filePath: string, source: string): CrapFunction[] {
  const extracted = typescriptExtractor.extract({ path: filePath, after: source });
  if (extracted instanceof Promise) throw new Error("crap-cli: async extractor unsupported");
  return extracted.functions.map((f) => ({
    name: f.name,
    startLine: f.startLine,
    endLine: f.endLine,
    cc: f.cyclomaticComplexity,
  }));
}

export function typescriptCrapAdapter(cwd: string): CrapAdapter {
  const snapshotPath = path.join(cwd, "coverage", "snapshot.json");
  return {
    snapshotExists: () => fs.existsSync(snapshotPath),
    snapshotMtime: () => fs.statSync(snapshotPath).mtimeMs / 1000,
    loadSnapshot: () => JSON.parse(fs.readFileSync(snapshotPath, "utf8")) as Snapshot,
    extractFunctions: extractCrapFunctions,
  };
}

function formatReport(violationsByFile: Record<string, CrapViolation[]>, threshold: number): string {
  const lines = [`crap: CRAP threshold exceeded (threshold=${threshold}):`];
  for (const [file, viols] of Object.entries(violationsByFile)) {
    for (const v of viols) {
      lines.push(`  ${file}:${v.name}  CC=${v.cc}  cov=${Math.round(v.cov * 100)}%  CRAP=${Math.round(v.crap)}`);
    }
  }
  return lines.join("\n");
}

export async function runCrap(opts: {
  cwd: string;
  adapter?: CrapAdapter;
  threshold?: number;
}): Promise<CrapResult> {
  const cwd = opts.cwd;
  const threshold = opts.threshold ?? DEFAULT_THRESHOLD;
  const adapter = opts.adapter ?? typescriptCrapAdapter(cwd);

  const candidates = stagedFiles(cwd)
    .filter((p) => detectLang(p) === "typescript")
    .filter((p) => !isSkippedPath(p));

  if (candidates.length === 0) return { status: 0, stderr: "" };

  if (!adapter.snapshotExists()) return { status: 1, stderr: `${MISSING_SNAPSHOT_MSG}\n` };

  const stale = staleStagedFile(cwd, candidates, adapter.snapshotMtime());
  if (stale !== null) return { status: 1, stderr: `${STALE_SNAPSHOT_MSG}\n` };

  const snapshot = adapter.loadSnapshot();
  const violationsByFile = collectViolations(cwd, candidates, adapter, snapshot, threshold);

  if (Object.keys(violationsByFile).length === 0) return { status: 0, stderr: "" };

  return { status: 1, stderr: `${formatReport(violationsByFile, threshold)}\n` };
}

function staleStagedFile(cwd: string, candidates: string[], snapshotMtime: number): string | null {
  for (const rel of candidates) {
    const abs = path.join(cwd, ...rel.split("/"));
    if (fs.existsSync(abs) && fs.statSync(abs).mtimeMs / 1000 > snapshotMtime) return rel;
  }
  return null;
}

function collectViolations(
  cwd: string,
  candidates: string[],
  adapter: CrapAdapter,
  snapshot: Snapshot,
  threshold: number,
): Record<string, CrapViolation[]> {
  const violationsByFile: Record<string, CrapViolation[]> = {};
  for (const rel of candidates) {
    const source = readSource(cwd, rel);
    if (source === null) continue;
    if (isGeneratedContent(source)) continue;

    const hunks = parseHunkRanges(gitText(cwd, ["diff", "--cached", "-U0", "--", rel]));
    if (hunks.length === 0) continue;

    const functions = adapter.extractFunctions(rel, source);
    const coverage = snapshot.files[rel] ?? "new";
    const violations = flagCrapViolations({ path: rel, functions, hunks, coverage, threshold });
    if (violations.length > 0) violationsByFile[rel] = violations;
  }
  return violationsByFile;
}

async function main(): Promise<void> {
  const res = await runCrap({ cwd: process.cwd() });
  if (res.stderr.length > 0) process.stderr.write(res.stderr);
  process.exit(res.status);
}

if (import.meta.main) {
  await main();
}
