const SKIP_PATH_SEGMENTS = new Set(["migrations", "playground"]);
const SKIP_FILENAME_SUFFIXES = ["_pb2.py", "_pb2_grpc.py"];
const HEADER_SCAN_LINES = 5;
const GENERATED_HEADER_PATTERNS = [
  /@generated/i,
  /generated by/i,
  /do not edit/i,
];

function basename(path: string): string {
  const slash = path.lastIndexOf("/");
  return slash === -1 ? path : path.slice(slash + 1);
}

function isSkippedPath(path: string): boolean {
  const segments = path.split("/");
  if (segments.some((seg) => SKIP_PATH_SEGMENTS.has(seg))) return true;
  const name = basename(path);
  return SKIP_FILENAME_SUFFIXES.some((suffix) => name.endsWith(suffix));
}

function isGeneratedContent(text: string): boolean {
  const header = text.split("\n", HEADER_SCAN_LINES).join("\n");
  return GENERATED_HEADER_PATTERNS.some((pattern) => pattern.test(header));
}

export function shouldSkip(path: string, text: string): boolean {
  return isSkippedPath(path) || isGeneratedContent(text);
}
