import { test } from "node:test";
import assert from "node:assert/strict";

import { shouldSkip } from "./prefilter.ts";

test("a path through migrations is skipped", () => {
  assert.equal(shouldSkip("db/migrations/0001_init.py", "x = 1"), true);
});

test("a path through playground is skipped", () => {
  assert.equal(shouldSkip("playground/exp.py", "x = 1"), true);
});

test("a path through a nested playground segment is skipped", () => {
  assert.equal(shouldSkip("pkg/playground/exp.py", "x = 1"), true);
});

test("a regular path is not skipped on path grounds", () => {
  assert.equal(shouldSkip("app/foo.py", "x = 1"), false);
});

test("a protobuf-generated python basename is skipped", () => {
  assert.equal(shouldSkip("proto/foo_pb2.py", "x = 1"), true);
});

test("a grpc-generated python basename is skipped", () => {
  assert.equal(shouldSkip("proto/foo_pb2_grpc.py", "x = 1"), true);
});

test("an at-generated header within the first five lines is skipped", () => {
  assert.equal(shouldSkip("app/foo.py", "@generated\nx = 1"), true);
});

test("a generated-by header within the first five lines is skipped", () => {
  assert.equal(shouldSkip("app/foo.py", "// Generated by protoc.\nx = 1"), true);
});

test("a do-not-edit header within the first five lines is skipped", () => {
  assert.equal(shouldSkip("app/foo.py", "// do not edit\nx = 1"), true);
});

test("a generated marker past the fifth line is not skipped on header grounds", () => {
  const text = ["a", "b", "c", "d", "e", "@generated"].join("\n");

  assert.equal(shouldSkip("app/foo.py", text), false);
});

test("a case-variant generated header still triggers a skip", () => {
  assert.equal(shouldSkip("app/foo.py", "@GENERATED\nx = 1"), true);
});

test("hand-written code is not skipped", () => {
  assert.equal(shouldSkip("app/foo.py", "def f():\n    return 1"), false);
});
